export const colors = {
  accentPeach: '#FAE5D8',
  background: '#FFFFFF',
  backgroundTint: '#F8F2EB',
  border: '#EBE4DA',
  card: '#FFFFFF',
  cardAlt: '#FAF6F0',
  cardRose: '#FFF6F8',
  cardSun: '#FFF8E6',
  primary: '#6BBF72',
  primaryDeep: '#4A9554',
  secondary: '#F26D85',
  secondaryDeep: '#C94F68',
  softPink: '#FEEAED',
  softYellow: '#FBF0C0',
  surfaceGreen: '#ECF5EA',
  surfaceMint: '#E4EFDF',
  surfaceRose: '#FBEAF0',
  text: '#243127',
  textMuted: '#667166',
  warning: '#F4C542',
};
